services:
  mysql:
    image: mysql:8.0
    container_name: studyverse-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mata
      MYSQL_DATABASE: studyverse
    volumes:
      - studyverse_mysql_data:/var/lib/mysql

volumes:
  studyverse_mysql_data:
